### ISSUE TITLE
How to get the MOST image data

### ISSUE THREAD

**Issue by WHUH-ML** [denizlab/OAI-MRI-TKR#1]
I noticed that your research used MRI data for external validation from the MOST database, but according to the description on the MOST official website, the image data will not be published until 2023. I would appreciate it if you could tell me how to get the MOST image data.
![image](https://user-images.githubusercontent.com/104161438/202898997-44c2485d-0cc7-4434-93b5-107fd47a8c13.png)

**Comment by cemmdeniz** [comment]
We obtained the data online from UCSF prior to their closeout: https://most.ucsfsitebuilder.acsitefactory.com/steps-obtaining-data-and-images Unfortunately, I do not know where/how to obtain images other than waiting for their release in the website you sent.
